/* station-registry.c generated by valac 0.34.2, the Vala compiler
 * generated from station-registry.vala, do not modify */

/* This file is part of Gradio.
 *
 * Gradio is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Gradio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Gradio.  If not, see <http://www.gnu.org/licenses/>.
 */

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gobject/gvaluecollector.h>


#define GRADIO_TYPE_STATION_REGISTRY (gradio_station_registry_get_type ())
#define GRADIO_STATION_REGISTRY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GRADIO_TYPE_STATION_REGISTRY, GradioStationRegistry))
#define GRADIO_STATION_REGISTRY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GRADIO_TYPE_STATION_REGISTRY, GradioStationRegistryClass))
#define GRADIO_IS_STATION_REGISTRY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GRADIO_TYPE_STATION_REGISTRY))
#define GRADIO_IS_STATION_REGISTRY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GRADIO_TYPE_STATION_REGISTRY))
#define GRADIO_STATION_REGISTRY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GRADIO_TYPE_STATION_REGISTRY, GradioStationRegistryClass))

typedef struct _GradioStationRegistry GradioStationRegistry;
typedef struct _GradioStationRegistryClass GradioStationRegistryClass;
typedef struct _GradioStationRegistryPrivate GradioStationRegistryPrivate;

#define GRADIO_TYPE_RADIO_STATION (gradio_radio_station_get_type ())
#define GRADIO_RADIO_STATION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GRADIO_TYPE_RADIO_STATION, GradioRadioStation))
#define GRADIO_RADIO_STATION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GRADIO_TYPE_RADIO_STATION, GradioRadioStationClass))
#define GRADIO_IS_RADIO_STATION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GRADIO_TYPE_RADIO_STATION))
#define GRADIO_IS_RADIO_STATION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GRADIO_TYPE_RADIO_STATION))
#define GRADIO_RADIO_STATION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GRADIO_TYPE_RADIO_STATION, GradioRadioStationClass))

typedef struct _GradioRadioStation GradioRadioStation;
typedef struct _GradioRadioStationClass GradioRadioStationClass;
typedef struct _GradioRadioStationPrivate GradioRadioStationPrivate;
typedef struct _GradioParamSpecStationRegistry GradioParamSpecStationRegistry;

struct _GradioStationRegistry {
	GTypeInstance parent_instance;
	volatile int ref_count;
	GradioStationRegistryPrivate * priv;
};

struct _GradioStationRegistryClass {
	GTypeClass parent_class;
	void (*finalize) (GradioStationRegistry *self);
};

struct _GradioRadioStation {
	GTypeInstance parent_instance;
	volatile int ref_count;
	GradioRadioStationPrivate * priv;
	gint counter_id;
	gchar* Title;
	gchar* Homepage;
	gchar* Language;
	gint ID;
	gchar* Icon;
	gchar* Country;
	gchar* Tags;
	gchar* State;
	gchar* Votes;
	gchar* Codec;
	gchar* Bitrate;
	gboolean Broken;
	gboolean is_playing;
	gboolean is_in_library;
};

struct _GradioRadioStationClass {
	GTypeClass parent_class;
	void (*finalize) (GradioRadioStation *self);
};

struct _GradioParamSpecStationRegistry {
	GParamSpec parent_instance;
};


static gpointer gradio_station_registry_parent_class = NULL;
extern gint gradio_station_registry_counter;
gint gradio_station_registry_counter = 0;
extern gint gradio_station_registry_active_stations;
gint gradio_station_registry_active_stations = 0;

gpointer gradio_station_registry_ref (gpointer instance);
void gradio_station_registry_unref (gpointer instance);
GParamSpec* gradio_param_spec_station_registry (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void gradio_value_set_station_registry (GValue* value, gpointer v_object);
void gradio_value_take_station_registry (GValue* value, gpointer v_object);
gpointer gradio_value_get_station_registry (const GValue* value);
GType gradio_station_registry_get_type (void) G_GNUC_CONST;
enum  {
	GRADIO_STATION_REGISTRY_DUMMY_PROPERTY
};
static GradioStationRegistry* gradio_station_registry_new (void);
static GradioStationRegistry* gradio_station_registry_construct (GType object_type);
gpointer gradio_radio_station_ref (gpointer instance);
void gradio_radio_station_unref (gpointer instance);
GParamSpec* gradio_param_spec_radio_station (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void gradio_value_set_radio_station (GValue* value, gpointer v_object);
void gradio_value_take_radio_station (GValue* value, gpointer v_object);
gpointer gradio_value_get_radio_station (const GValue* value);
GType gradio_radio_station_get_type (void) G_GNUC_CONST;
gint gradio_station_registry_register_station (GradioRadioStation* s);
static void gradio_station_registry_added_to_library_handler (gint cid);
static void _gradio_station_registry_added_to_library_handler_gradio_radio_station_added_to_library (GradioRadioStation* _sender, gint cid, gpointer self);
static void gradio_station_registry_removed_from_library_handler (gint cid);
static void _gradio_station_registry_removed_from_library_handler_gradio_radio_station_removed_from_library (GradioRadioStation* _sender, gint cid, gpointer self);
static void gradio_station_registry_playing_handler (gint cid);
static void _gradio_station_registry_playing_handler_gradio_radio_station_played (GradioRadioStation* _sender, gint cid, gpointer self);
void gradio_station_registry_unregister_station (GradioRadioStation* s);
static void gradio_station_registry_finalize (GradioStationRegistry* obj);


static GradioStationRegistry* gradio_station_registry_construct (GType object_type) {
	GradioStationRegistry* self = NULL;
	self = (GradioStationRegistry*) g_type_create_instance (object_type);
	return self;
}


static GradioStationRegistry* gradio_station_registry_new (void) {
	return gradio_station_registry_construct (GRADIO_TYPE_STATION_REGISTRY);
}


static void _gradio_station_registry_added_to_library_handler_gradio_radio_station_added_to_library (GradioRadioStation* _sender, gint cid, gpointer self) {
	gradio_station_registry_added_to_library_handler (cid);
}


static void _gradio_station_registry_removed_from_library_handler_gradio_radio_station_removed_from_library (GradioRadioStation* _sender, gint cid, gpointer self) {
	gradio_station_registry_removed_from_library_handler (cid);
}


static void _gradio_station_registry_playing_handler_gradio_radio_station_played (GradioRadioStation* _sender, gint cid, gpointer self) {
	gradio_station_registry_playing_handler (cid);
}


gint gradio_station_registry_register_station (GradioRadioStation* s) {
	gint result = 0;
	gint _tmp0_ = 0;
	gint _tmp1_ = 0;
	GradioRadioStation* _tmp2_ = NULL;
	GradioRadioStation* _tmp3_ = NULL;
	GradioRadioStation* _tmp4_ = NULL;
	gint _tmp5_ = 0;
	GradioRadioStation* _tmp6_ = NULL;
	const gchar* _tmp7_ = NULL;
	gint _tmp8_ = 0;
	gint _tmp9_ = 0;
	g_return_val_if_fail (s != NULL, 0);
	_tmp0_ = gradio_station_registry_counter;
	gradio_station_registry_counter = _tmp0_ + 1;
	_tmp1_ = gradio_station_registry_active_stations;
	gradio_station_registry_active_stations = _tmp1_ + 1;
	_tmp2_ = s;
	g_signal_connect (_tmp2_, "added-to-library", (GCallback) _gradio_station_registry_added_to_library_handler_gradio_radio_station_added_to_library, NULL);
	_tmp3_ = s;
	g_signal_connect (_tmp3_, "removed-from-library", (GCallback) _gradio_station_registry_removed_from_library_handler_gradio_radio_station_removed_from_library, NULL);
	_tmp4_ = s;
	g_signal_connect (_tmp4_, "played", (GCallback) _gradio_station_registry_playing_handler_gradio_radio_station_played, NULL);
	_tmp5_ = gradio_station_registry_counter;
	_tmp6_ = s;
	_tmp7_ = _tmp6_->Title;
	_tmp8_ = gradio_station_registry_active_stations;
	g_message ("station-registry.vala:35: [%i] \"%s\" is registered. (%i active statio" \
"ns)", _tmp5_, _tmp7_, _tmp8_);
	_tmp9_ = gradio_station_registry_counter;
	result = _tmp9_;
	return result;
}


void gradio_station_registry_unregister_station (GradioRadioStation* s) {
	gint _tmp0_ = 0;
	GradioRadioStation* _tmp1_ = NULL;
	guint _tmp2_ = 0U;
	GradioRadioStation* _tmp3_ = NULL;
	guint _tmp4_ = 0U;
	GradioRadioStation* _tmp5_ = NULL;
	guint _tmp6_ = 0U;
	gint _tmp7_ = 0;
	GradioRadioStation* _tmp8_ = NULL;
	const gchar* _tmp9_ = NULL;
	gint _tmp10_ = 0;
	g_return_if_fail (s != NULL);
	_tmp0_ = gradio_station_registry_active_stations;
	gradio_station_registry_active_stations = _tmp0_ - 1;
	_tmp1_ = s;
	g_signal_parse_name ("added-to-library", GRADIO_TYPE_RADIO_STATION, &_tmp2_, NULL, FALSE);
	g_signal_handlers_disconnect_matched (_tmp1_, G_SIGNAL_MATCH_ID | G_SIGNAL_MATCH_FUNC | G_SIGNAL_MATCH_DATA, _tmp2_, 0, NULL, (GCallback) _gradio_station_registry_added_to_library_handler_gradio_radio_station_added_to_library, NULL);
	_tmp3_ = s;
	g_signal_parse_name ("removed-from-library", GRADIO_TYPE_RADIO_STATION, &_tmp4_, NULL, FALSE);
	g_signal_handlers_disconnect_matched (_tmp3_, G_SIGNAL_MATCH_ID | G_SIGNAL_MATCH_FUNC | G_SIGNAL_MATCH_DATA, _tmp4_, 0, NULL, (GCallback) _gradio_station_registry_removed_from_library_handler_gradio_radio_station_removed_from_library, NULL);
	_tmp5_ = s;
	g_signal_parse_name ("played", GRADIO_TYPE_RADIO_STATION, &_tmp6_, NULL, FALSE);
	g_signal_handlers_disconnect_matched (_tmp5_, G_SIGNAL_MATCH_ID | G_SIGNAL_MATCH_FUNC | G_SIGNAL_MATCH_DATA, _tmp6_, 0, NULL, (GCallback) _gradio_station_registry_playing_handler_gradio_radio_station_played, NULL);
	_tmp7_ = gradio_station_registry_counter;
	_tmp8_ = s;
	_tmp9_ = _tmp8_->Title;
	_tmp10_ = gradio_station_registry_active_stations;
	g_message ("station-registry.vala:46: [%i] \"%s\" is unregistered (%i active stati" \
"ons)", _tmp7_, _tmp9_, _tmp10_);
}


static void gradio_station_registry_added_to_library_handler (gint cid) {
	gint _tmp0_ = 0;
	_tmp0_ = cid;
	g_message ("station-registry.vala:50: [%i] added to library", _tmp0_);
}


static void gradio_station_registry_removed_from_library_handler (gint cid) {
	gint _tmp0_ = 0;
	_tmp0_ = cid;
	g_message ("station-registry.vala:54: [%i] removed from library", _tmp0_);
}


static void gradio_station_registry_playing_handler (gint cid) {
	gint _tmp0_ = 0;
	_tmp0_ = cid;
	g_message ("station-registry.vala:58: [%i] is now playing", _tmp0_);
}


static void gradio_value_station_registry_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void gradio_value_station_registry_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		gradio_station_registry_unref (value->data[0].v_pointer);
	}
}


static void gradio_value_station_registry_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = gradio_station_registry_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer gradio_value_station_registry_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* gradio_value_station_registry_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		GradioStationRegistry* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = gradio_station_registry_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* gradio_value_station_registry_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	GradioStationRegistry** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = gradio_station_registry_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec* gradio_param_spec_station_registry (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	GradioParamSpecStationRegistry* spec;
	g_return_val_if_fail (g_type_is_a (object_type, GRADIO_TYPE_STATION_REGISTRY), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer gradio_value_get_station_registry (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, GRADIO_TYPE_STATION_REGISTRY), NULL);
	return value->data[0].v_pointer;
}


void gradio_value_set_station_registry (GValue* value, gpointer v_object) {
	GradioStationRegistry* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, GRADIO_TYPE_STATION_REGISTRY));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, GRADIO_TYPE_STATION_REGISTRY));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		gradio_station_registry_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		gradio_station_registry_unref (old);
	}
}


void gradio_value_take_station_registry (GValue* value, gpointer v_object) {
	GradioStationRegistry* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, GRADIO_TYPE_STATION_REGISTRY));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, GRADIO_TYPE_STATION_REGISTRY));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		gradio_station_registry_unref (old);
	}
}


static void gradio_station_registry_class_init (GradioStationRegistryClass * klass) {
	gradio_station_registry_parent_class = g_type_class_peek_parent (klass);
	((GradioStationRegistryClass *) klass)->finalize = gradio_station_registry_finalize;
}


static void gradio_station_registry_instance_init (GradioStationRegistry * self) {
	self->ref_count = 1;
}


static void gradio_station_registry_finalize (GradioStationRegistry* obj) {
	GradioStationRegistry * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, GRADIO_TYPE_STATION_REGISTRY, GradioStationRegistry);
	g_signal_handlers_destroy (self);
}


GType gradio_station_registry_get_type (void) {
	static volatile gsize gradio_station_registry_type_id__volatile = 0;
	if (g_once_init_enter (&gradio_station_registry_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { gradio_value_station_registry_init, gradio_value_station_registry_free_value, gradio_value_station_registry_copy_value, gradio_value_station_registry_peek_pointer, "p", gradio_value_station_registry_collect_value, "p", gradio_value_station_registry_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (GradioStationRegistryClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) gradio_station_registry_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GradioStationRegistry), 0, (GInstanceInitFunc) gradio_station_registry_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType gradio_station_registry_type_id;
		gradio_station_registry_type_id = g_type_register_fundamental (g_type_fundamental_next (), "GradioStationRegistry", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&gradio_station_registry_type_id__volatile, gradio_station_registry_type_id);
	}
	return gradio_station_registry_type_id__volatile;
}


gpointer gradio_station_registry_ref (gpointer instance) {
	GradioStationRegistry* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void gradio_station_registry_unref (gpointer instance) {
	GradioStationRegistry* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		GRADIO_STATION_REGISTRY_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}



