/* gradio.c generated by valac 0.34.0, the Vala compiler
 * generated from gradio.vala, do not modify */

/* This file is part of Gradio.
 *
 * Gradio is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Gradio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Gradio.  If not, see <http://www.gnu.org/licenses/>.
 */

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <gio/gio.h>
#include <stdlib.h>
#include <string.h>
#include <glib/gi18n-lib.h>
#include <gst/gst.h>


#define GRADIO_TYPE_APP (gradio_app_get_type ())
#define GRADIO_APP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GRADIO_TYPE_APP, GradioApp))
#define GRADIO_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GRADIO_TYPE_APP, GradioAppClass))
#define GRADIO_IS_APP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GRADIO_TYPE_APP))
#define GRADIO_IS_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GRADIO_TYPE_APP))
#define GRADIO_APP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GRADIO_TYPE_APP, GradioAppClass))

typedef struct _GradioApp GradioApp;
typedef struct _GradioAppClass GradioAppClass;
typedef struct _GradioAppPrivate GradioAppPrivate;

#define GRADIO_TYPE_IMAGE_PROVIDER (gradio_image_provider_get_type ())
#define GRADIO_IMAGE_PROVIDER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GRADIO_TYPE_IMAGE_PROVIDER, GradioImageProvider))
#define GRADIO_IMAGE_PROVIDER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GRADIO_TYPE_IMAGE_PROVIDER, GradioImageProviderClass))
#define GRADIO_IS_IMAGE_PROVIDER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GRADIO_TYPE_IMAGE_PROVIDER))
#define GRADIO_IS_IMAGE_PROVIDER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GRADIO_TYPE_IMAGE_PROVIDER))
#define GRADIO_IMAGE_PROVIDER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GRADIO_TYPE_IMAGE_PROVIDER, GradioImageProviderClass))

typedef struct _GradioImageProvider GradioImageProvider;
typedef struct _GradioImageProviderClass GradioImageProviderClass;

#define GRADIO_TYPE_MAIN_WINDOW (gradio_main_window_get_type ())
#define GRADIO_MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GRADIO_TYPE_MAIN_WINDOW, GradioMainWindow))
#define GRADIO_MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GRADIO_TYPE_MAIN_WINDOW, GradioMainWindowClass))
#define GRADIO_IS_MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GRADIO_TYPE_MAIN_WINDOW))
#define GRADIO_IS_MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GRADIO_TYPE_MAIN_WINDOW))
#define GRADIO_MAIN_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GRADIO_TYPE_MAIN_WINDOW, GradioMainWindowClass))

typedef struct _GradioMainWindow GradioMainWindow;
typedef struct _GradioMainWindowClass GradioMainWindowClass;

#define GRADIO_TYPE_AUDIO_PLAYER (gradio_audio_player_get_type ())
#define GRADIO_AUDIO_PLAYER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GRADIO_TYPE_AUDIO_PLAYER, GradioAudioPlayer))
#define GRADIO_AUDIO_PLAYER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GRADIO_TYPE_AUDIO_PLAYER, GradioAudioPlayerClass))
#define GRADIO_IS_AUDIO_PLAYER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GRADIO_TYPE_AUDIO_PLAYER))
#define GRADIO_IS_AUDIO_PLAYER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GRADIO_TYPE_AUDIO_PLAYER))
#define GRADIO_AUDIO_PLAYER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GRADIO_TYPE_AUDIO_PLAYER, GradioAudioPlayerClass))

typedef struct _GradioAudioPlayer GradioAudioPlayer;
typedef struct _GradioAudioPlayerClass GradioAudioPlayerClass;

#define GRADIO_TYPE_LIBRARY (gradio_library_get_type ())
#define GRADIO_LIBRARY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GRADIO_TYPE_LIBRARY, GradioLibrary))
#define GRADIO_LIBRARY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GRADIO_TYPE_LIBRARY, GradioLibraryClass))
#define GRADIO_IS_LIBRARY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GRADIO_TYPE_LIBRARY))
#define GRADIO_IS_LIBRARY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GRADIO_TYPE_LIBRARY))
#define GRADIO_LIBRARY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GRADIO_TYPE_LIBRARY, GradioLibraryClass))

typedef struct _GradioLibrary GradioLibrary;
typedef struct _GradioLibraryClass GradioLibraryClass;

#define GRADIO_TYPE_MPRIS (gradio_mpris_get_type ())
#define GRADIO_MPRIS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GRADIO_TYPE_MPRIS, GradioMPRIS))
#define GRADIO_MPRIS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GRADIO_TYPE_MPRIS, GradioMPRISClass))
#define GRADIO_IS_MPRIS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GRADIO_TYPE_MPRIS))
#define GRADIO_IS_MPRIS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GRADIO_TYPE_MPRIS))
#define GRADIO_MPRIS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GRADIO_TYPE_MPRIS, GradioMPRISClass))

typedef struct _GradioMPRIS GradioMPRIS;
typedef struct _GradioMPRISClass GradioMPRISClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _gradio_image_provider_unref0(var) ((var == NULL) ? NULL : (var = (gradio_image_provider_unref (var), NULL)))

#define GRADIO_TYPE_RELEASE_NOTES_WINDOW (gradio_release_notes_window_get_type ())
#define GRADIO_RELEASE_NOTES_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GRADIO_TYPE_RELEASE_NOTES_WINDOW, GradioReleaseNotesWindow))
#define GRADIO_RELEASE_NOTES_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GRADIO_TYPE_RELEASE_NOTES_WINDOW, GradioReleaseNotesWindowClass))
#define GRADIO_IS_RELEASE_NOTES_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GRADIO_TYPE_RELEASE_NOTES_WINDOW))
#define GRADIO_IS_RELEASE_NOTES_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GRADIO_TYPE_RELEASE_NOTES_WINDOW))
#define GRADIO_RELEASE_NOTES_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GRADIO_TYPE_RELEASE_NOTES_WINDOW, GradioReleaseNotesWindowClass))

typedef struct _GradioReleaseNotesWindow GradioReleaseNotesWindow;
typedef struct _GradioReleaseNotesWindowClass GradioReleaseNotesWindowClass;

#define GRADIO_TYPE_SETTINGS_WINDOW (gradio_settings_window_get_type ())
#define GRADIO_SETTINGS_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GRADIO_TYPE_SETTINGS_WINDOW, GradioSettingsWindow))
#define GRADIO_SETTINGS_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GRADIO_TYPE_SETTINGS_WINDOW, GradioSettingsWindowClass))
#define GRADIO_IS_SETTINGS_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GRADIO_TYPE_SETTINGS_WINDOW))
#define GRADIO_IS_SETTINGS_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GRADIO_TYPE_SETTINGS_WINDOW))
#define GRADIO_SETTINGS_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GRADIO_TYPE_SETTINGS_WINDOW, GradioSettingsWindowClass))

typedef struct _GradioSettingsWindow GradioSettingsWindow;
typedef struct _GradioSettingsWindowClass GradioSettingsWindowClass;

struct _GradioApp {
	GtkApplication parent_instance;
	GradioAppPrivate * priv;
};

struct _GradioAppClass {
	GtkApplicationClass parent_class;
};

struct _GradioAppPrivate {
	GtkMenu* menuSystem;
};


static gpointer gradio_app_parent_class = NULL;
extern GradioImageProvider* gradio_app_imgprovider;
GradioImageProvider* gradio_app_imgprovider = NULL;
extern GradioMainWindow* gradio_app_window;
GradioMainWindow* gradio_app_window = NULL;
extern GradioAudioPlayer* gradio_app_player;
GradioAudioPlayer* gradio_app_player = NULL;
extern GradioLibrary* gradio_app_library;
GradioLibrary* gradio_app_library = NULL;
extern GSettings* gradio_app_settings;
GSettings* gradio_app_settings = NULL;
extern GradioMPRIS* gradio_app_mpris;
GradioMPRIS* gradio_app_mpris = NULL;

GType gradio_app_get_type (void) G_GNUC_CONST;
#define GRADIO_APP_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), GRADIO_TYPE_APP, GradioAppPrivate))
enum  {
	GRADIO_APP_DUMMY_PROPERTY
};
gpointer gradio_image_provider_ref (gpointer instance);
void gradio_image_provider_unref (gpointer instance);
GParamSpec* gradio_param_spec_image_provider (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void gradio_value_set_image_provider (GValue* value, gpointer v_object);
void gradio_value_take_image_provider (GValue* value, gpointer v_object);
gpointer gradio_value_get_image_provider (const GValue* value);
GType gradio_image_provider_get_type (void) G_GNUC_CONST;
GType gradio_main_window_get_type (void) G_GNUC_CONST;
GType gradio_audio_player_get_type (void) G_GNUC_CONST;
GType gradio_library_get_type (void) G_GNUC_CONST;
GType gradio_mpris_get_type (void) G_GNUC_CONST;
GradioApp* gradio_app_new (void);
GradioApp* gradio_app_construct (GType object_type);
static void gradio_app_restore_window (GradioApp* self);
static void _gradio_app_restore_window_gtk_status_icon_activate (GtkStatusIcon* _sender, gpointer self);
static void gradio_app_create_menuSystem (GradioApp* self);
static void gradio_app_menuSystem_popup (GradioApp* self, guint button, guint time);
static void _gradio_app_menuSystem_popup_gtk_status_icon_popup_menu (GtkStatusIcon* _sender, guint button, guint activate_time, gpointer self);
static void gradio_app_real_activate (GApplication* base);
GradioLibrary* gradio_library_new (void);
GradioLibrary* gradio_library_construct (GType object_type);
void gradio_library_read_data (GradioLibrary* self);
static void gradio_app_create_app_menu (GradioApp* self);
GradioAudioPlayer* gradio_audio_player_new (void);
GradioAudioPlayer* gradio_audio_player_construct (GType object_type);
GradioMPRIS* gradio_mpris_new (void);
GradioMPRIS* gradio_mpris_construct (GType object_type);
void gradio_mpris_initialize (GradioMPRIS* self);
GradioImageProvider* gradio_image_provider_new (void);
GradioImageProvider* gradio_image_provider_construct (GType object_type);
GradioMainWindow* gradio_main_window_new (GradioApp* app);
GradioMainWindow* gradio_main_window_construct (GType object_type, GradioApp* app);
static void gradio_app_connect_signals (GradioApp* self);
gboolean util_check_database_connection (void);
void gradio_main_window_show_no_connection_message (GradioMainWindow* self);
void gradio_app_report_an_error (GradioApp* self);
void util_open_website (const gchar* address);
void gradio_app_release_notes (GradioApp* self);
GType gradio_release_notes_window_get_type (void) G_GNUC_CONST;
GradioReleaseNotesWindow* gradio_release_notes_window_new (void);
GradioReleaseNotesWindow* gradio_release_notes_window_construct (GType object_type);
static void gradio_app_show_preferences_dialog (GradioApp* self);
GType gradio_settings_window_get_type (void) G_GNUC_CONST;
GradioSettingsWindow* gradio_settings_window_new (void);
GradioSettingsWindow* gradio_settings_window_construct (GType object_type);
static void gradio_app_show_about_dialog (GradioApp* self);
static void __lambda71_ (GradioApp* self);
static void ___lambda71__g_simple_action_activate (GSimpleAction* _sender, GVariant* parameter, gpointer self);
static void __lambda84_ (GradioApp* self);
static void ___lambda84__g_simple_action_activate (GSimpleAction* _sender, GVariant* parameter, gpointer self);
static void __lambda85_ (GradioApp* self);
void gradio_app_quit_application (GradioApp* self);
static void ___lambda85__g_simple_action_activate (GSimpleAction* _sender, GVariant* parameter, gpointer self);
static void __lambda86_ (GradioApp* self);
static void ___lambda86__g_simple_action_activate (GSimpleAction* _sender, GVariant* parameter, gpointer self);
static void __lambda87_ (GradioApp* self);
static void ___lambda87__g_simple_action_activate (GSimpleAction* _sender, GVariant* parameter, gpointer self);
static void __lambda88_ (GradioApp* self, GradioAudioPlayer* o, const gchar* t);
void util_show_info_dialog (const gchar* text, GtkWindow* parent);
static void ___lambda88__gradio_audio_player_connection_error (GradioAudioPlayer* _sender, const gchar* text, gpointer self);
void gradio_main_window_save_geometry (GradioMainWindow* self);
static void gradio_app_play_and_stop (GradioApp* self);
void gradio_audio_player_toggle_play_stop (GradioAudioPlayer* self);
static void _gradio_app_play_and_stop_gtk_menu_item_activate (GtkMenuItem* _sender, gpointer self);
static void _gradio_app_quit_application_gtk_menu_item_activate (GtkMenuItem* _sender, gpointer self);
static void gradio_app_finalize (GObject* obj);
gint gradio_main (gchar** args, int args_length1);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);


static void _gradio_app_restore_window_gtk_status_icon_activate (GtkStatusIcon* _sender, gpointer self) {
	gradio_app_restore_window ((GradioApp*) self);
}


static void _gradio_app_menuSystem_popup_gtk_status_icon_popup_menu (GtkStatusIcon* _sender, guint button, guint activate_time, gpointer self) {
	gradio_app_menuSystem_popup ((GradioApp*) self, button, activate_time);
}


GradioApp* gradio_app_construct (GType object_type) {
	GradioApp * self = NULL;
	GSettings* _tmp0_ = NULL;
	GtkStatusIcon* trayicon = NULL;
	GtkStatusIcon* _tmp1_ = NULL;
	_tmp0_ = g_settings_new ("de.haecker-felix.gradio");
	_g_object_unref0 (gradio_app_settings);
	gradio_app_settings = _tmp0_;
	self = (GradioApp*) g_object_new (object_type, "application-id", "de.haeckerfelix.gradio", "flags", G_APPLICATION_FLAGS_NONE, NULL);
	_tmp1_ = gtk_status_icon_new_from_icon_name ("gradio");
	trayicon = _tmp1_;
	g_signal_connect_object (trayicon, "activate", (GCallback) _gradio_app_restore_window_gtk_status_icon_activate, self, 0);
	gradio_app_create_menuSystem (self);
	g_signal_connect_object (trayicon, "popup-menu", (GCallback) _gradio_app_menuSystem_popup_gtk_status_icon_popup_menu, self, 0);
	_g_object_unref0 (trayicon);
	return self;
}


GradioApp* gradio_app_new (void) {
	return gradio_app_construct (GRADIO_TYPE_APP);
}


static void gradio_app_real_activate (GApplication* base) {
	GradioApp * self;
	GradioLibrary* _tmp0_ = NULL;
	GradioLibrary* _tmp1_ = NULL;
	GradioAudioPlayer* _tmp2_ = NULL;
	GradioMPRIS* _tmp3_ = NULL;
	GradioMPRIS* _tmp4_ = NULL;
	GradioImageProvider* _tmp5_ = NULL;
	GradioMainWindow* _tmp6_ = NULL;
	GradioMainWindow* _tmp7_ = NULL;
	GradioMainWindow* _tmp8_ = NULL;
	gboolean _tmp9_ = FALSE;
	self = (GradioApp*) base;
	_tmp0_ = gradio_library_new ();
	g_object_ref_sink (_tmp0_);
	_g_object_unref0 (gradio_app_library);
	gradio_app_library = _tmp0_;
	_tmp1_ = gradio_app_library;
	gradio_library_read_data (_tmp1_);
	gradio_app_create_app_menu (self);
	_tmp2_ = gradio_audio_player_new ();
	_g_object_unref0 (gradio_app_player);
	gradio_app_player = _tmp2_;
	_tmp3_ = gradio_mpris_new ();
	_g_object_unref0 (gradio_app_mpris);
	gradio_app_mpris = _tmp3_;
	_tmp4_ = gradio_app_mpris;
	gradio_mpris_initialize (_tmp4_);
	_tmp5_ = gradio_image_provider_new ();
	_gradio_image_provider_unref0 (gradio_app_imgprovider);
	gradio_app_imgprovider = _tmp5_;
	_tmp6_ = gradio_main_window_new (self);
	g_object_ref_sink (_tmp6_);
	_g_object_unref0 (gradio_app_window);
	gradio_app_window = _tmp6_;
	_tmp7_ = gradio_app_window;
	gtk_application_add_window ((GtkApplication*) self, (GtkWindow*) _tmp7_);
	_tmp8_ = gradio_app_window;
	gtk_widget_show_all ((GtkWidget*) _tmp8_);
	gradio_app_connect_signals (self);
	_tmp9_ = util_check_database_connection ();
	if (!_tmp9_) {
		GradioMainWindow* _tmp10_ = NULL;
		_tmp10_ = gradio_app_window;
		gradio_main_window_show_no_connection_message (_tmp10_);
	}
}


void gradio_app_report_an_error (GradioApp* self) {
	g_return_if_fail (self != NULL);
	util_open_website ("https://github.com/haecker-felix/gradio/issues/new");
}


void gradio_app_release_notes (GradioApp* self) {
	GradioReleaseNotesWindow* rn = NULL;
	GradioReleaseNotesWindow* _tmp0_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = gradio_release_notes_window_new ();
	g_object_ref_sink (_tmp0_);
	rn = _tmp0_;
	gtk_widget_show_all ((GtkWidget*) rn);
	_g_object_unref0 (rn);
}


static void gradio_app_show_preferences_dialog (GradioApp* self) {
	GradioSettingsWindow* swindow = NULL;
	GradioSettingsWindow* _tmp0_ = NULL;
	GradioMainWindow* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = gradio_settings_window_new ();
	g_object_ref_sink (_tmp0_);
	swindow = _tmp0_;
	_tmp1_ = gradio_app_window;
	gtk_window_set_transient_for ((GtkWindow*) swindow, (GtkWindow*) _tmp1_);
	gtk_widget_show ((GtkWidget*) swindow);
	_g_object_unref0 (swindow);
}


static void gradio_app_show_about_dialog (GradioApp* self) {
	gchar** authors = NULL;
	gchar* _tmp0_ = NULL;
	gchar** _tmp1_ = NULL;
	gint authors_length1 = 0;
	gint _authors_size_ = 0;
	gchar** artists = NULL;
	gchar* _tmp2_ = NULL;
	gchar** _tmp3_ = NULL;
	gint artists_length1 = 0;
	gint _artists_size_ = 0;
	GradioMainWindow* _tmp4_ = NULL;
	const gchar* _tmp5_ = NULL;
	const gchar* _tmp6_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_strdup ("Felix Häcker <haecker.felix1207@gmail.com>");
	_tmp1_ = g_new0 (gchar*, 1 + 1);
	_tmp1_[0] = _tmp0_;
	authors = _tmp1_;
	authors_length1 = 1;
	_authors_size_ = authors_length1;
	_tmp2_ = g_strdup ("Juan Pablo Lozano <lozanotux@gmail.com>");
	_tmp3_ = g_new0 (gchar*, 1 + 1);
	_tmp3_[0] = _tmp2_;
	artists = _tmp3_;
	artists_length1 = 1;
	_artists_size_ = artists_length1;
	_tmp4_ = gradio_app_window;
	_tmp5_ = _ ("translator-credits");
	_tmp6_ = _ ("About Gradio");
	gtk_show_about_dialog ((GtkWindow*) _tmp4_, "artists", artists, "authors", authors, "translator-credits", _tmp5_, "program-name", "Gradio", "title", _tmp6_, "license-type", GTK_LICENSE_GPL_3_0, "logo-icon-name", "de.haeckerfelix.gradio", "version", VERSION, "comments", "Database: www.radio-browser.info", "website", "https://github.com/haecker-felix/gradio", "wrap-license", TRUE, NULL);
	artists = (_vala_array_free (artists, artists_length1, (GDestroyNotify) g_free), NULL);
	authors = (_vala_array_free (authors, authors_length1, (GDestroyNotify) g_free), NULL);
}


static void __lambda71_ (GradioApp* self) {
	gradio_app_show_preferences_dialog (self);
}


static void ___lambda71__g_simple_action_activate (GSimpleAction* _sender, GVariant* parameter, gpointer self) {
	__lambda71_ ((GradioApp*) self);
}


static void __lambda84_ (GradioApp* self) {
	gradio_app_show_about_dialog (self);
}


static void ___lambda84__g_simple_action_activate (GSimpleAction* _sender, GVariant* parameter, gpointer self) {
	__lambda84_ ((GradioApp*) self);
}


static void __lambda85_ (GradioApp* self) {
	gradio_app_quit_application (self);
}


static void ___lambda85__g_simple_action_activate (GSimpleAction* _sender, GVariant* parameter, gpointer self) {
	__lambda85_ ((GradioApp*) self);
}


static void __lambda86_ (GradioApp* self) {
	gradio_app_release_notes (self);
}


static void ___lambda86__g_simple_action_activate (GSimpleAction* _sender, GVariant* parameter, gpointer self) {
	__lambda86_ ((GradioApp*) self);
}


static void __lambda87_ (GradioApp* self) {
	gradio_app_report_an_error (self);
}


static void ___lambda87__g_simple_action_activate (GSimpleAction* _sender, GVariant* parameter, gpointer self) {
	__lambda87_ ((GradioApp*) self);
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static void gradio_app_create_app_menu (GradioApp* self) {
	GSimpleAction* action = NULL;
	GSimpleAction* _tmp0_ = NULL;
	GSimpleAction* _tmp1_ = NULL;
	GSimpleAction* _tmp2_ = NULL;
	GSimpleAction* _tmp3_ = NULL;
	GSimpleAction* _tmp4_ = NULL;
	GSimpleAction* _tmp5_ = NULL;
	GSimpleAction* _tmp6_ = NULL;
	GSimpleAction* _tmp7_ = NULL;
	GSimpleAction* _tmp8_ = NULL;
	GSimpleAction* _tmp9_ = NULL;
	GSimpleAction* _tmp10_ = NULL;
	GSimpleAction* _tmp11_ = NULL;
	GSimpleAction* _tmp12_ = NULL;
	GSimpleAction* _tmp13_ = NULL;
	GSimpleAction* _tmp14_ = NULL;
	GtkBuilder* builder = NULL;
	GtkBuilder* _tmp15_ = NULL;
	GMenuModel* app_menu = NULL;
	GObject* _tmp16_ = NULL;
	GMenuModel* _tmp17_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_simple_action_new ("preferences", NULL);
	action = _tmp0_;
	_tmp1_ = action;
	g_signal_connect_object (_tmp1_, "activate", (GCallback) ___lambda71__g_simple_action_activate, self, 0);
	_tmp2_ = action;
	g_action_map_add_action ((GActionMap*) self, (GAction*) _tmp2_);
	_tmp3_ = g_simple_action_new ("about", NULL);
	_g_object_unref0 (action);
	action = _tmp3_;
	_tmp4_ = action;
	g_signal_connect_object (_tmp4_, "activate", (GCallback) ___lambda84__g_simple_action_activate, self, 0);
	_tmp5_ = action;
	g_action_map_add_action ((GActionMap*) self, (GAction*) _tmp5_);
	_tmp6_ = g_simple_action_new ("quit", NULL);
	_g_object_unref0 (action);
	action = _tmp6_;
	_tmp7_ = action;
	g_signal_connect_object (_tmp7_, "activate", (GCallback) ___lambda85__g_simple_action_activate, self, 0);
	_tmp8_ = action;
	g_action_map_add_action ((GActionMap*) self, (GAction*) _tmp8_);
	_tmp9_ = g_simple_action_new ("release_notes", NULL);
	_g_object_unref0 (action);
	action = _tmp9_;
	_tmp10_ = action;
	g_signal_connect_object (_tmp10_, "activate", (GCallback) ___lambda86__g_simple_action_activate, self, 0);
	_tmp11_ = action;
	g_action_map_add_action ((GActionMap*) self, (GAction*) _tmp11_);
	_tmp12_ = g_simple_action_new ("report_an_error", NULL);
	_g_object_unref0 (action);
	action = _tmp12_;
	_tmp13_ = action;
	g_signal_connect_object (_tmp13_, "activate", (GCallback) ___lambda87__g_simple_action_activate, self, 0);
	_tmp14_ = action;
	g_action_map_add_action ((GActionMap*) self, (GAction*) _tmp14_);
	_tmp15_ = gtk_builder_new_from_resource ("/de/haecker-felix/gradio/app-menu.ui");
	builder = _tmp15_;
	_tmp16_ = gtk_builder_get_object (builder, "app-menu");
	_tmp17_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp16_, g_menu_model_get_type ()) ? ((GMenuModel*) _tmp16_) : NULL);
	app_menu = _tmp17_;
	gtk_application_set_app_menu ((GtkApplication*) self, app_menu);
	_g_object_unref0 (app_menu);
	_g_object_unref0 (builder);
	_g_object_unref0 (action);
}


static void __lambda88_ (GradioApp* self, GradioAudioPlayer* o, const gchar* t) {
	const gchar* _tmp0_ = NULL;
	GradioMainWindow* _tmp1_ = NULL;
	g_return_if_fail (o != NULL);
	g_return_if_fail (t != NULL);
	_tmp0_ = t;
	_tmp1_ = gradio_app_window;
	util_show_info_dialog (_tmp0_, (GtkWindow*) _tmp1_);
	return;
}


static void ___lambda88__gradio_audio_player_connection_error (GradioAudioPlayer* _sender, const gchar* text, gpointer self) {
	__lambda88_ ((GradioApp*) self, _sender, text);
}


static void gradio_app_connect_signals (GradioApp* self) {
	GradioAudioPlayer* _tmp0_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = gradio_app_player;
	g_signal_connect_object (_tmp0_, "connection-error", (GCallback) ___lambda88__gradio_audio_player_connection_error, self, 0);
}


static void gradio_app_restore_window (GradioApp* self) {
	GtkWindow* active_window = NULL;
	GtkWindow* _tmp0_ = NULL;
	GtkWindow* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = gtk_application_get_active_window ((GtkApplication*) self);
	_tmp1_ = _g_object_ref0 (_tmp0_);
	active_window = _tmp1_;
	gtk_window_present (active_window);
	_g_object_unref0 (active_window);
}


void gradio_app_quit_application (GradioApp* self) {
	GradioMainWindow* _tmp0_ = NULL;
	g_return_if_fail (self != NULL);
	gradio_app_restore_window (self);
	_tmp0_ = gradio_app_window;
	gradio_main_window_save_geometry (_tmp0_);
	g_application_quit ((GApplication*) G_TYPE_CHECK_INSTANCE_CAST (self, gtk_application_get_type (), GtkApplication));
}


static void gradio_app_play_and_stop (GradioApp* self) {
	GradioAudioPlayer* _tmp0_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = gradio_app_player;
	gradio_audio_player_toggle_play_stop (_tmp0_);
}


static void _gradio_app_play_and_stop_gtk_menu_item_activate (GtkMenuItem* _sender, gpointer self) {
	gradio_app_play_and_stop ((GradioApp*) self);
}


static void _gradio_app_quit_application_gtk_menu_item_activate (GtkMenuItem* _sender, gpointer self) {
	gradio_app_quit_application ((GradioApp*) self);
}


static void gradio_app_create_menuSystem (GradioApp* self) {
	GtkMenu* _tmp0_ = NULL;
	GtkMenuItem* menuPlayStop = NULL;
	GtkMenuItem* _tmp1_ = NULL;
	GtkMenu* _tmp2_ = NULL;
	GtkImageMenuItem* menuQuit = NULL;
	GtkImageMenuItem* _tmp3_ = NULL;
	GtkMenu* _tmp4_ = NULL;
	GtkMenu* _tmp5_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = (GtkMenu*) gtk_menu_new ();
	g_object_ref_sink (_tmp0_);
	_g_object_unref0 (self->priv->menuSystem);
	self->priv->menuSystem = _tmp0_;
	_tmp1_ = (GtkMenuItem*) gtk_menu_item_new_with_label ("Play / Stop");
	g_object_ref_sink (_tmp1_);
	menuPlayStop = _tmp1_;
	g_signal_connect_object (menuPlayStop, "activate", (GCallback) _gradio_app_play_and_stop_gtk_menu_item_activate, self, 0);
	_tmp2_ = self->priv->menuSystem;
	gtk_menu_shell_append ((GtkMenuShell*) _tmp2_, (GtkWidget*) menuPlayStop);
	_tmp3_ = (GtkImageMenuItem*) gtk_image_menu_item_new_from_stock (GTK_STOCK_QUIT, NULL);
	g_object_ref_sink (_tmp3_);
	menuQuit = _tmp3_;
	g_signal_connect_object ((GtkMenuItem*) menuQuit, "activate", (GCallback) _gradio_app_quit_application_gtk_menu_item_activate, self, 0);
	_tmp4_ = self->priv->menuSystem;
	gtk_menu_shell_append ((GtkMenuShell*) _tmp4_, (GtkWidget*) ((GtkMenuItem*) menuQuit));
	_tmp5_ = self->priv->menuSystem;
	gtk_widget_show_all ((GtkWidget*) _tmp5_);
	_g_object_unref0 (menuQuit);
	_g_object_unref0 (menuPlayStop);
}


static void gradio_app_menuSystem_popup (GradioApp* self, guint button, guint time) {
	GtkMenu* _tmp0_ = NULL;
	guint _tmp1_ = 0U;
	guint _tmp2_ = 0U;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->menuSystem;
	_tmp1_ = button;
	_tmp2_ = time;
	gtk_menu_popup (_tmp0_, NULL, NULL, NULL, NULL, _tmp1_, (guint32) _tmp2_);
}


static void gradio_app_class_init (GradioAppClass * klass) {
	gradio_app_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (GradioAppPrivate));
	((GApplicationClass *) klass)->activate = gradio_app_real_activate;
	G_OBJECT_CLASS (klass)->finalize = gradio_app_finalize;
}


static void gradio_app_instance_init (GradioApp * self) {
	self->priv = GRADIO_APP_GET_PRIVATE (self);
}


static void gradio_app_finalize (GObject* obj) {
	GradioApp * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, GRADIO_TYPE_APP, GradioApp);
	_g_object_unref0 (self->priv->menuSystem);
	G_OBJECT_CLASS (gradio_app_parent_class)->finalize (obj);
}


GType gradio_app_get_type (void) {
	static volatile gsize gradio_app_type_id__volatile = 0;
	if (g_once_init_enter (&gradio_app_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (GradioAppClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) gradio_app_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GradioApp), 0, (GInstanceInitFunc) gradio_app_instance_init, NULL };
		GType gradio_app_type_id;
		gradio_app_type_id = g_type_register_static (gtk_application_get_type (), "GradioApp", &g_define_type_info, 0);
		g_once_init_leave (&gradio_app_type_id__volatile, gradio_app_type_id);
	}
	return gradio_app_type_id__volatile;
}


gint gradio_main (gchar** args, int args_length1) {
	gint result = 0;
	GradioApp* app = NULL;
	GradioApp* _tmp0_ = NULL;
	gchar** _tmp1_ = NULL;
	gint _tmp1__length1 = 0;
	g_message ("gradio.vala:171: %s", "Starting Gradio version " VERSION "!");
	gst_init (&args_length1, &args);
	gtk_init (&args_length1, &args);
	_tmp0_ = gradio_app_new ();
	app = _tmp0_;
	_tmp1_ = args;
	_tmp1__length1 = args_length1;
	g_application_run ((GApplication*) app, _tmp1__length1, _tmp1_);
	result = 0;
	_g_object_unref0 (app);
	return result;
}


int main (int argc, char ** argv) {
#if !GLIB_CHECK_VERSION (2,35,0)
	g_type_init ();
#endif
	return gradio_main (argv, argc);
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}



