/* main.c generated by valac 0.34.0, the Vala compiler
 * generated from main.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gst/gst.h>
#include <gtk/gtk.h>
#include <gio/gio.h>


#define GRADIO_TYPE_APP (gradio_app_get_type ())
#define GRADIO_APP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GRADIO_TYPE_APP, GradioApp))
#define GRADIO_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GRADIO_TYPE_APP, GradioAppClass))
#define GRADIO_IS_APP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GRADIO_TYPE_APP))
#define GRADIO_IS_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GRADIO_TYPE_APP))
#define GRADIO_APP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GRADIO_TYPE_APP, GradioAppClass))

typedef struct _GradioApp GradioApp;
typedef struct _GradioAppClass GradioAppClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))



gint gradio_main (gchar** args, int args_length1);
GType gradio_app_get_type (void) G_GNUC_CONST;
GradioApp* gradio_app_new (void);
GradioApp* gradio_app_construct (GType object_type);


gint gradio_main (gchar** args, int args_length1) {
	gint result = 0;
	GradioApp* app = NULL;
	GradioApp* _tmp0_ = NULL;
	gchar** _tmp1_ = NULL;
	gint _tmp1__length1 = 0;
	g_message ("main.vala:6: %s", "Starting Gradio version " VERSION "!");
	gst_init (&args_length1, &args);
	gtk_init (&args_length1, &args);
	_tmp0_ = gradio_app_new ();
	app = _tmp0_;
	_tmp1_ = args;
	_tmp1__length1 = args_length1;
	g_application_run ((GApplication*) app, _tmp1__length1, _tmp1_);
	result = 0;
	_g_object_unref0 (app);
	return result;
}


int main (int argc, char ** argv) {
#if !GLIB_CHECK_VERSION (2,35,0)
	g_type_init ();
#endif
	return gradio_main (argv, argc);
}



